# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('GammaNN_rcpp_hello', PACKAGE = 'GammaNN')
}
test <- function() {
  .Call('GammaNN_test', PACKAGE = 'GammaNN');
}
learn <- function(frame, hidden, units, trace_size, eps, batch_size, random_patterns, max_epoch_number) {
  .Call('GammaNN_learn',
        frame, hidden, units, trace_size,
        eps, batch_size, random_patterns,
        max_epoch_number,
        PACKAGE = 'GammaNN'
  );
}
get_series <- function(NN, object_numbers) {
  .Call('GammaNN_get_series',
        NN, object_numbers,
        PACKAGE = 'GammaNN'
  );
}
get_series_name <- function(NN) {
  .Call('GammaNN_get_series_name',
        NN,
        PACKAGE = 'GammaNN'
  );
}
get_series_length <- function(NN) {
  .Call('GammaNN_get_series_length',
        NN,
        PACKAGE = 'GammaNN'
  );
}
get_src_series_length <- function(NN) {
  .Call('GammaNN_get_src_series_length',
        NN,
        PACKAGE = 'GammaNN'
  );
}
to_GammaNN <- function(str) {
  .Call('GammaNN_to_GammaNN',
        str,
        PACKAGE = 'GammaNN'
  );
}
to_str <- function(NN) {
  .Call('GammaNN_to_str',
        NN,
        PACKAGE = 'GammaNN'
  );
}
create_from_file <- function(file_path) {
  .Call('GammaNN_create_from_file',
        file_path,
        PACKAGE = 'GammaNN'
  );
}
write_to_file <- function(NN, file_path) {
  .Call('GammaNN_write_to_file',
        NN, file_path,
        PACKAGE = 'GammaNN'
  );
}

#future_src - frame that containes several future points
#this function returns data.frame with first step predictions using future_src parameter
first_step_prediction_test <- function(NN, future_src_frame) {
  .Call('GammaNN_first_step_prediction_test',
        NN, future_src_frame,
        PACKAGE = 'GammaNN'
  );
}
