// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello
Rcpp::List rcpp_hello();
RcppExport SEXP GammaNN_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

// test
Rcpp::RObject test();
RcppExport SEXP GammaNN_test() {
  BEGIN_RCPP
  return Rcpp::wrap(test());
  END_RCPP
}
